### ISSUE TITLE
Potentially refactor to use `prd` and `modulo` libraries

### ISSUE THREAD

**Issue by wyatt-howe** [lapets/lagrange#3]
https://github.com/lapets/lagrange/blob/9ef2d9d640e1e02f8a196af6f8b8c85877d2e5b2/src/lagrange/lagrange.py#L231-L244

The above could probably be simplified further if we would use the [`prd`](https://github.com/lapets/prd) and [`modulo`](https://github.com/lapets/modulo) libraries, maybe to look something like this:

```python
     prd(
         [values[x]] + [ 
             # Extrapolate using the fact that *y* = ``1`` if 
             # ``x`` = ``x_known``, and *y* = ``0`` for the other 
             # known values in the domain. 
             div(0 - x_known, x - x_known) 
             for x_known in xs if x_known is not x 
         ]
     )
```
This may negatively affect performance.

**Comment by lapets** [comment]
The suggested refactoring/simplification is applied in f0103bb1e350a6c7915790a1030585f1f268d149. The additional dependencies were not introduced due to the modulus attribute storage overhead of the [`modulo`](https://github.com/lapets/modulo) library.
